[tool.poetry]
name = "scripts"
version = "0.1.0"
description = ""
authors = ["elpapi42 <whitman-2@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.19.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
